---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yml
  - install.yaml
  - ingress.yml
  - conf/projects/project-team-devops.yml
  - conf/applications/application-argocd.yml
  - conf/applications/application-traefik.yml
  - conf/applications/application-vote.yml

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    files:
      - conf/repositories

secretGenerator:
  - name: argocd-secret
    behavior: merge
    literals:
      - admin.password=$2a$10$.l./Ge2D8wl.vP662RpX7.1bxyb26dxsWzG3ZPWBCy2M9M9EE2wuK # demo
      - admin.passwordMtime=2020-12-15T18:18:58Z
