---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yml
  - install.yaml
  - ingress.yml
  - conf/projects/project-team-devops.yml
  - conf/applications/application-traefik.yml
  - conf/applications/application-argocd.yml
  - conf/applications/application-vote.yml

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    files:
      - conf/repositories
