---
apiVersion: gitlab.com/maltcommunity
kind: SopsDecoder
metadata:
  name: gitlab-app-config-deploy-key
name: gitlab-app-config-deploy-key
files:
  - path: ../../secrets/gitlab-deploy-key.enc
    key_name: sshPrivateKey
    type: raw
options:
  disableNameSuffixHash: true
---
apiVersion: gitlab.com/maltcommunity
kind: SopsDecoder
metadata:
  name: google-serviceaccount
name: google-serviceaccount
files:
  - path: ../../secrets/google-serviceaccount.enc.json
    key_name: serviceaccount.json
    type: json
options:
  disableNameSuffixHash: true