---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yml
  - traefik-rbac.yml
  - traefik-crd.yml
  - traefik-pvc.yml
  - traefik-svc.yml
  - traefik-svc-lb.yml
  - traefik-deployment.yml
  - whoami.yml

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
  - name: traefik-config
    behavior: create
    files:
      - config/traefik.toml