apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: traefik
  name: traefik-acme
  namespace: traefik
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
