---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
bases:
  - ../base

# Fetch variables from configmap
vars:
- name: DNS_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: apps-config
  fieldref:
    fieldpath: data.DNS_NAME

configMapGenerator:
  - name: apps-config
    behavior: create
    literals:
      - DNS_NAME=demo
