---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
bases:
  - ../base

configMapGenerator:
  - name: apps-config
    behavior: merge
    literals:
      - DNS_NAME=domain.com


