[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[serversTransport]
  insecureSkipVerify = true

[log]
  level = "info"
  #format = "json"

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
      middlewares = ["compress@file", "ratelimit@file", "security-headers@file"]
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
      permanent = true
  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http]
      middlewares = ["compress@file", "ratelimit@file", "security-headers@file"]
    [entryPoints.websecure.transport]
      [entryPoints.websecure.transport.respondingTimeouts]
        readTimeout = "180s"
        writeTimeout = "180s"
        idleTimeout = "540s"
      [entryPoints.websecure.transport.lifeCycle]
        requestAcceptGraceTimeout = "90s"
        graceTimeOut = "30s"
    [entryPoints.websecure.http.tls]
  [entryPoints.metrics]
    address = ":9100"
  [entryPoints.ping]
    address = ":8082"

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/tls/tls.crt"
      keyFile  = "/tls/tls.key"

[ping]
  entryPoint = "ping"

[providers]
  [providers.kubernetesCRD]
  [providers.kubernetesIngress]
    [providers.kubernetesIngress.ingressEndpoint]
      publishedService = "traefik/traefik-lb"
  [providers.file]
    directory = "/config"
    watch = true

#[acme]
#  KeyType = "RSA4096"
#  email = "foo@example.com"
#  storage = "/acme/acme.json"
#  entryPoint = "websecure"
#  onHostRule = true
#  [acme.tlsChallenge]

[api]
  dashboard = true

[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"