---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
bases:
  - ../base

generatorOptions:
 disableNameSuffixHash: true

# generate a ConfigMap named nodejs-config.
configMapGenerator:
  - name: traefik-config
    behavior: merge
    literals:
      - DNS_NAME=demo
    files:
      - config/dynamic.toml

# secret containing traefik ingress certificate
secretGenerator:
  - name: traefik-default-cert
    behavior: create
    files:
      - config/tls.key
      - config/tls.crt

# Sops Generator used to create secret from sops encrypted file
# https://github.com/mozilla/sops
# generators:
#   - sops-decoder.yml

# Fetch variables from configmap
vars:
- name: DNS_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: traefik-config
  fieldref:
    fieldpath: data.DNS_NAME

