apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: demo-vote
  namespace: argocd
spec:
  destination:
    namespace: vote
    server: https://kubernetes.default.svc
  project: default
  source:
    path: vote-app/dev
    repoURL: https://gitlab.com/seuf/argocd-demo.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
