apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-devops
  namespace: argocd
spec:
  description: devops Team
  destinations:
  - namespace: apps
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: traefik
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: "rbac.authorization.k8s.io"
    kind: ClusterRole
  - group: "rbac.authorization.k8s.io"
    kind: ClusterRoleBinding
  - group: ""
    kind: Namespace
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  namespaceResourceBlacklist:
  - group: ""
    kind: ResourceQuota
  - group: ""
    kind: LimitRange
  - group: ""
    kind: NetworkPolicy
  orphanedResources:
    warn: false
  roles:
  - description: Sync privileges for devops platform applications
    jwtTokens:
    - iat: 1585650056
    name: ci-role
    policies:
    - p, proj:team-devops:ci-role, applications, sync, team-devops/*, allow
    - p, proj:team-devops:ci-role, applications, override, team-devops/*, allow
    - p, proj:team-devops:ci-role, applications, update, team-devops/*, allow
  sourceRepos:
  - git@gitlab.com:seuf/argocd-demo.git
