apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: result
  namespace: vote
spec:
  rules:
  - host: result.$(DNS_NAME)
    http:
      paths:
      - backend:
          serviceName: result
          servicePort: 80
        path: /
