apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vote
  namespace: apps
spec:
  rules:
  - host: vote.$(DNS_NAME)
    http:
      paths:
      - backend:
          serviceName: vote
          servicePort: 80
        path: /
