---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
bases:
  - ../base

vars:
  - name: DNS_DOMAIN
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: argocd
    fieldref:
      fieldpath: data.DNS_DOMAIN

configMapGenerator:
  - name: argocd
    behavior: create
    literals:
      - environment-type=staging
      - environment=dev
      - DNS_DOMAIN=demo